### ISSUE TITLE
Disabled in dev

### ISSUE THREAD

**Issue by GWillmann** [hamaryuginh/GoogleAnalyticsBundle#1]
Hi there, thanks for this wonderful bundle !
It would be great if we could disable the tracking in dev environment.

Adding something like enabled: true in config.yml
and enabled: false in config_dev.yml.

I could try to pull request you a solution but I am not sure it will be in the cleanest way...

[UPDATE]
I created a pull request for this improvement!

**Comment by hamaryuginh** [comment]
Thanks for the pull request, it's merged :)
